apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-deploy
  template:
    metadata:
      labels:
        app: java-deploy
    spec:
      containers:
      - name: java-deploy
        image: 123456789101234/cicd-java:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000   # (non-root user id)
